name: exist2023-ai-upv
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - libsqlite=3.43.0
  - libzlib=1.2.13
  - ncurses=6.4
  - openssl=3.1.3
  - pip=23.2.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.41.2
  - xz=5.4.2
  - pip:
      - argparse==1.4.0
      - beautifulsoup4==4.12.2
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - filelock==3.12.4
      - fsspec==2023.9.2
      - gdown==4.7.1
      - huggingface-hub==0.17.3
      - idna==3.4
      - jinja2==3.1.2
      - markupsafe==2.1.3
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.26.0
      - packaging==23.2
      - pandas==2.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - regex==2023.10.3
      - requests==2.31.0
      - safetensors==0.4.0
      - six==1.16.0
      - soupsieve==2.5
      - sympy==1.12
      - tokenizers==0.14.1
      - torch==2.1.0
      - tqdm==4.66.1
      - transformers==4.34.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==2.0.6
